labelUserInput <- function()
{
        source("Data_Grouping.R")
        fileName <- readline(prompt = "Enter File Name (complete filePath): ")

        a <- groupDataFunction(fileName)
        print("Please enter label number for each line :")
        print("Labels")
        print("1 - Name")
        print("2 - PhoneNumber1")
        print("3 - PhoneNumber2")
        print("4 - FaxNumber")
        print("5 - CompanyName")
        print("6 - AddressLine1")
        print("7 - AddressLine2")
        print("8 - AddressLine3")
        print("9 - EmailAddress1")
        print("10 - EmailAddress2")
        print("11 - WebSite")
        print("12 - Designation")
        print("13 - Ignore Text")
        print("14 - Name + Designation")
        return(a)
}